name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '⚒️ Continous Integration'
    label: 'ci'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⬆️ Dependency Updates'
    label: 'dependencies'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/prism-be/Prism.Nemi.NemiSante/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
